# Generated by Django 4.1.1 on 2022-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_posting_alter_department_options_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
