# Generated by Django 4.1.1 on 2022-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_posting_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
