# Generated by Django 4.1.1 on 2022-09-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_posting_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='position',
            new_name='post',
        ),
    ]
