# Generated by Django 4.1.1 on 2022-09-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
