# Generated by Django 4.1.1 on 2022-09-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_geeksmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
