# Generated by Django 4.1.1 on 2022-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M1', models.IntegerField()),
                ('M2', models.IntegerField()),
                ('M3', models.IntegerField()),
                ('M4', models.IntegerField()),
                ('M5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
